blank_issues_enabled: false
contact_links:
  - name: Bugs, Feedback, Feature Requests, and Questions
    url: https://feedback.yaak.app
    about: "Please report to Yaak's public feedback board. Issues will be created and linked here when applicable."
